comerciov2/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('principal.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('ordenes/', include('ordenes.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordenes/urls.py
from django.urls import path
from . import views

app_name = 'ordenes'

urlpatterns = [
    path('agregar/', views.agregar_carrito, name="agregar"),
    path('carrito/', views.lista_carrito, name="lista_carrito"),
    path('comprar/', views.comprar, name="comprar"),
    path('cancelar-carrito/', views.cancelar_carrito, name='cancelar_carrito')
]

principal/urls.py
from django.urls import path

from . import views

app_name = 'principal'

urlpatterns = [
    # Home de la pagina
    path('', views.index, name='principal'),
    path('admin/', views.admin, name='admin'),

    # Listado de productos/servicios
    path('lista/', views.lista, name='lista'),

    # Listado de productos/servicios para administradores
    path('lista_admin/', views.lista_admin, name='lista_admin'),

    path('lista_productos_vendedor/', views.lista_productos,
         name='lista_prod_vendedor'),

    # CRUD Productos
    path('nuevo_producto/', views.NuevoProducto.as_view(), name='nuevo_producto'),
    path('editar_producto/<int:pk>',
         views.EditarProducto.as_view(), name='editar_producto'),
    path('eliminar_producto/<int:pk>',
         views.EliminarProducto.as_view(), name='eliminar_producto'),
    path('ver_producto/<int:pk>', views.VerProducto.as_view(), name='ver_producto'),
    path('nuevo_producto_vendedor/', views.AgregarProductoVendedor.as_view(),
         name='nuevo_producto_vendedor'),


    # CRUD Servicios
    path(
        'nuevo_servicio/',
        views.NuevoServicio.as_view(),
        name='nuevo_servicio'),
    path(
        'eliminar_servicio/<int:pk>',
        views.EliminarServicio.as_view(),
        name='eliminar_servicio')
]

principal/models.py
from django.db import models


class Producto(models.Model):
    vendedor = models.ForeignKey(
        'usuarios.Usuario_Vendedor',
        verbose_name='Vendedor',
        on_delete=models.CASCADE, blank=False, null=False)
    nombre = models.CharField(max_length=30, blank=False, null=False)
    imagen = models.ImageField(
        "Imagen",
        upload_to='principal',
        blank=True,
        null=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=0)
    categoria = models.CharField(max_length=50, blank=False, null=False)
    descripcion = models.CharField(
        "Descripción",
        max_length=250,
        null=True,
        blank=True)

    def __str__(self):
        return self.nombre


class Servicio(models.Model):
    vendedor = models.ForeignKey(
        'usuarios.Usuario',
        verbose_name='Vendedor',
        on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50, blank=False, null=False)
    imagen = models.ImageField(
        "Imagen",
        upload_to='principal',
        blank=True,
        null=True)
    descripcion = models.TextField(
        "Descripción",
        max_length=250,
        null=True,
        blank=True)
    categoria = models.CharField(max_length=50, blank=False, null=False)

principal/forms.py
from django import forms
from django.forms import Textarea
from .models import Producto, Servicio


class ProductoForm(forms.ModelForm):

    class Meta:
        model = Producto

        fields = '__all__'

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': Textarea(attrs={'cols': 20, 'rows': 5}),

        }


class ProductoFormVendedor(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': Textarea(attrs={'cols': 20, 'rows': 5}),

        }


class ServicioForm(forms.ModelForm):
    class Meta:
        model = Servicio

        fields = '__all__'

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'})
        }

principal/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .forms import ProductoForm, ProductoFormVendedor, ServicioForm
from .models import Producto, Servicio
from django.contrib.auth.decorators import login_required

# Home del sitio


def index(request):
    productos = Producto.objects.all()[:3]
    servicios = Servicio.objects.all()[:3]

    return render(
        request, 'index.html', {
            'productos': productos, 'servicios': servicios})


def admin(request):
    return render(request, 'admin.html', {})


# Listado de productos/servicios
def lista(request):
    productos = Producto.objects.all()
    servicios = Servicio.objects.all()

    return render(request, 'principal/lista.html',
                  {'productos': productos, 'servicios': servicios})


@login_required
def lista_productos(request):
    productos = Producto.objects.filter(vendedor=request.user)
    # servicios = Servicio.objects.all()

    return render(request, 'principal/lista_vendedor.html',
                  {'productos': productos})

# Listado de productos/servicios para administradores


def lista_admin(request):
    productos = Producto.objects.all()
    servicios = Servicio.objects.all()

    return render(request, 'principal/lista_admin.html',
                  {'productos': productos, 'servicios': servicios})

# CRUD Productos


class NuevoProducto(PermissionRequiredMixin, CreateView):
    permission_required = 'usuarios.permiso'
    model = Producto
    form_class = ProductoForm
    template_name = 'principal/nuevo_producto.html'
    success_url = reverse_lazy('principal:lista_admin')

    extra_context = {
        'etiqueta': "Nuevo",
        'boton': "Agregar",
    }


class NuevoProductoVendedor(CreateView):
    template_name = 'principal\\producto_form_vendedor.html'
    model = Producto
    form_class = ProductoFormVendedor
    success_url = reverse_lazy('principal/lista')
    extra_context = {
        'etiqueta': "Nuevo",
        'boton': "Agregar",
    }


class EditarProducto(PermissionRequiredMixin, UpdateView):
    # permission_required = 'usuarios.permiso_administradores'
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy('principal:lista_admin')


class EditarProducto(PermissionRequiredMixin, UpdateView):
    permission_required = 'usuarios.permiso_administradores'
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy('principal:lista_admin')

    extra_context = {
        'etiqueta': "Actualizar",
        'boton': "Guardar",
    }


class EliminarProducto(DeleteView):
    # permission_required = 'usuarios.permiso_administradores'
    model = Producto
    success_url = reverse_lazy('principal:lista_admin')


class VerProducto(DetailView):
    model = Producto
    template_name = "principal/detalleProducto.html"
    context_object_name = "producto"

# CRUD Servicios


class NuevoServicio(PermissionRequiredMixin, CreateView):
    permission_required = 'usuarios.permiso_administradores'
    model = Servicio
    form_class = ServicioForm
    success_url = reverse_lazy('principal:lista_admin')


class EditarServicio(PermissionRequiredMixin, UpdateView):
    permission_required = 'usuarios.permiso_administradores'
    model = Servicio
    form_class = ServicioForm
    success_url = reverse_lazy('principal:lista_admin')


class EliminarServicio(PermissionRequiredMixin, DeleteView):
    permission_required = 'usuarios.permiso_administradores'
    model = Servicio
    success_url = reverse_lazy('principal:lista_admin')


class AgregarProductoVendedor(PermissionRequiredMixin, CreateView):
    # usuario_actual = request.user
    permission_required = 'usuarios.permiso_vendedores'
    model = Producto
    form_class = ProductoForm
    template_name = "principal/nuevo_producto_vendedor.html"

    def form_valid(self, form):
        obj = form.save(commit=False)
        # obj.vendedor = self.request.user
        obj.save()
        # success_url = reverse_lazy('principal:lista_prod_vendedor')
        productos = Producto.objects.filter(vendedor=self.request.user)
        return render(self.request, 'principal/lista_vendedor.html', {'productos': productos})

principal/templates/principal/detalleProducto.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Ver producto
{% endblock title %}

{% block body %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-sm-6">
                <div class="product-style-1 mt-30">
                    <div class="product-image">
                        <span class="icon-text text-style-1">Nuevo</span>
                        <div class="product-active">
                            <div class="product-item active">
                                <img src="{% if producto.imagen %}/media/{{MEDIA_URL}}{{producto.imagen}}{% else %}{% static 'images/product_placeholder.png' %}{% endif %}"
                                    alt="{{producto.nombre}}">
                            </div>
                        </div>
                    </div>
                    <div class="product-content text-center">
                        <h4 class="title"><a
                                href="{% url 'principal:ver_producto' producto.id %}">{{producto.nombre}}</a></h4>
                        <form action="{% url 'ordenes:agregar'%}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{producto.id}}">
                            <button type="submit" class="main-btn secondary-1-btn">
                                <img src="{% static 'images/icon-svg/cart-7.svg' %}" alt="">
                                ${{producto.precio}}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">

            </div>
        </div>
    </div>


</section>
{% endblock body %}

principal/templates/principal/lista.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	Lista de Productos/Servicios
{% endblock title %}

{% block body %}
	<section class="product-wrapper pt-30 pb-30">
		<div class="container">
			<divd class="row">
				{% for p in productos %}
					<div class="col-lg-4 col-sm-6">
						<div class="product-style-1 mt-100">
							<div class="product-image">
								<span class="icon-text text-style-1">Nuevo</span>
								<div class="product-active">
									<div class="product-item active">
										<img src="{% if p.imagen %}/media/{{MEDIA_URL}}{{p.imagen}}{% else %}{% static 'images/product_placeholder.png' %}{% endif %}" class="rounded mx-auto" alt="{{p.nombre}}">
									</div>
								</div>
							</div>
							<div class="product-content text-center">
								<h4 class="title"><a href="{% url 'principal:ver_producto' p.id %}">{{p.nombre}}</a></h4>
								<form action="{% url 'ordenes:agregar'%}" method="post">
									{% csrf_token %}
									<input type="hidden" name="id" value="{{p.id}}">
									<button type="submit" class="main-btn secondary-1-btn">
										<img src="{% static 'images/icon-svg/cart-7.svg' %}" alt="">
										${{p.precio}}
									</button>
								</form>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</section>

	<section class="product-wrapper pt-100 pb-70">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
				</div>
			</div>
			<div class="row">
				{% for s in servicios %}
					<div class="col-lg-4 col-sm-6">
						<div class="product-style-1 mt-30">
							<div class="product-image">
								<span class="icon-text text-style-1">Nuevo</span>
								<div class="product-active">
									<div class="product-item active">
										<img src="{% if s.imagen %}/media/{{MEDIA_URL}}{{s.imagen}}{% else %}{% static 'images/product_placeholder.png' %}{% endif %}" alt="{{s.nombre}}">
									</div>
								</div>
							</div>
							<div class="product-content text-center">
								<h4 class="title"><a href="{% url 'principal:ver_producto' p.id %}">{{p.nombre}}</a></h4>
								<form action="{% url 'ordenes:agregar'%}" method="post">
									{% csrf_token %}
									<input type="hidden" name="id" value="{{s.id}}">
									<button type="submit" class="main-btn secondary-1-btn">
										<img src="{% static 'images/icon-svg/cart-7.svg' %}" alt="">
										${{s.precio}}
									</button>
								</form>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</section>
	
{% endblock body %}


<!--====== Product Style 1 Part Start ======-->

principal/templates/principal/lista_admin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	Lista de Productos
{% endblock title %}

{% block body %}
	<h1>Lista de Productos/Servicios</h1>
	<br>
	
	<a  class="btn btn-primary" href="{% url 'principal:nuevo_producto' %}"><i class="fa fa-plus"> </i> Nuevo Producto</a> | 
	<a  class="btn btn-primary" href="{% url 'principal:nuevo_servicio' %}"><i class="fa fa-plus"> </i> Nuevo Servicio</a>

	<br>
	<table class="table" style='margin-top: 1em'>
		<thead>
			<th>ID</th>
			<th>Nombre</th>
			<th>Vendedor</th>
			<th>Precio</th>
			<th>Stock</th>
			<th>Descripción</th>
			<th><i class="fa fa-cog"></i> Opciones</th>
		</thead>
		<tbody>
			{% for p in productos %}
				<input type="hidden" name="id" value="{{p.id}}">
				<tr>
					<td>{{p.id}}</td>
					<td>{{p.nombre}}</td>
					<td>{{p.vendedor}}</td>
					<td>${{p.precio}}</td>
					<td>{{p.stock}}</td>
					<td>{{p.descripcion}}</td>
					<td>
						<a href="{% url 'principal:editar_producto' p.id %}"><i class="fa fa-edit"></i> Editar</a> |
						<a href="{% url 'principal:eliminar_producto' p.id %}"><i class="fa fa-trash"></i> Eliminar</a>
					</td>
				</tr>
			{% endfor %}
			
			{% for s in servicios %}
				<input type="hidden" name="id" value="{{p.id}}">
				<tr>
					<td>{{s.id}}</td>
					<td>{{s.nombre}}</td>
					<td>-</td>
					<td>-</td>
					<td>{{s.descripcion}}</td>
					<td>
						<a href="{% url 'principal:editar_servicio' s.id %}"><i class="fa fa-edit"></i> Editar</a> |
						<a href="{% url 'principal:eliminar_servicio' s.id %}"><i class="fa fa-trash"></i> Eliminar</a>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock body%}

{block js}
<script src="{% static 'js/funciones.js'%}"></script>
{endblock js}

principal/templates/principal/lista_vendedor.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	Lista de Productos
{% endblock title %}

{% block body %}

<br>
<div class="card-body">
    <h1>Lista de Productos/Servicios</h1>
    <br>
    <div class="card-content justify-content-end"> 
        <a class="btn btn-primary boton-ingresar" href="{% url 'principal:nuevo_producto_vendedor' %}"><i class="fa fa-plus"> </i> Nuevo Producto</a>
    </div>
    <br>
	<table class="table" style='margin-top: 1em'>
		<thead>
			<th>ID</th>
			<th>Nombre</th>
			<th>Vendedor</th>
			<th>Precio</th>
			<th>Stock</th>
			<th>Descripción</th>
			<th><i class="fa fa-cog"></i> Opciones</th>
		</thead>
		<tbody>
			{% for p in productos %}
				<input type="hidden" name="id" value="{{p.id}}">
				<tr>
					<td>{{p.id}}</td>
					<td>{{p.nombre}}</td>
					<td>{{p.vendedor}}</td>
					<td>${{p.precio}}</td>
					<td>{{p.stock}}</td>
					<td>{{p.descripcion}}</td>
					<td>
						<a href="{% url 'principal:editar_producto' p.id %}"><i class="fa fa-edit"></i> Editar</a> |
						<a href="{% url 'principal:eliminar_producto' p.id %}"><i class="fa fa-trash"></i> Eliminar</a>
					</td>
				</tr>
			{% endfor %}
        </tbody>
	</table>
</div>

{% endblock body %}

principal/templates/principal/nuevo_producto.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Nuevo Producto
{% endblock title%}
{% block body %}
{% load crispy_forms_tags%}

<br>
<div class="row">
	<div class="col-12 col-md-6 offset-md-3">
		<div class="card">
			<div class="card-body">
				<h1>Nuevo Producto</h1>
				<form method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{{form | crispy }}
					{% comment %} {{ form.vendedor | as_crispy_field }} {% endcomment %}
				
				<br>
				<button type="submit" class="btn btn-primary">Agregar</button>
				</form>
			</div>
		</div>
	</div>
</div>


{% endblock body %}

{% block js %}
<script src="{% static 'js/funciones.js'%}"></script>
{% endblock js %}

principal/templates/principal/nuevo_producto_vendedor.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Nuevo Producto
{% endblock title%}

{% block body %}
{% load crispy_forms_tags%}

<br>
<div class="row">
	<div class="col-12 col-md-6 offset-md-3">
		<div class="card">
			<div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% comment %} {{form.vendedor | as_crispy_field}} {% endcomment %}
                    {{form.vendedor | as_crispy_field}}
                    {{ form.nombre | as_crispy_field }}
                    {{ form.imagen | as_crispy_field }}
                    {{ form.precio | as_crispy_field }}
                    {{ form.stock | as_crispy_field }}
                    {{ form.categoria | as_crispy_field }}
                    {{ form.descripcion | as_crispy_field }}
                    
                    <br>
                    <br>
                    <div class = "d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary boton-ingresar justify-content-end">Agregar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{%endblock body%}

principal/templates/principal/producto_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Eliminar Producto
{% endblock title %}

{% block body %}
{% load crispy_forms_tags%}
<br>
<div class="row">
	<div class="col-12 col-md-6 offset-md-3">
		<div class="card">
			<div class="card-body">
				<form method="post">
					{% csrf_token %}
					<h1>Quieres eliminar el producto "{{ object }}"?</h1>
					<input class="btn btn-success" type="submit" value="Si, si quiero">
					<a class="btn btn-danger" href="{% url 'principal:lista_admin' %}"><i class="fa fa-times"> </i>Mejor no</a>
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock body %}

principal/templates/principal/producto_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{etiqueta}} Producto
{% endblock title %}

{% block css %}
{% endblock css %}

{% block body %}
{% load crispy_forms_tags%}

<br>
<div class="container justify-content-center">
	<div class="row">
		<div class="col-12 col-md-6 offset-md-3">
			<div class="card text-dark border-primary mb-3" style="max-width: 35rem;">
				<div class="card-body">
					<h4 class="card-title mb-4 mt-1">Producto</h4>
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}

						{{form | crispy }}
						<br>

						<div class="d-flex justify-content-end">
							<button type="submit" class="btn btn-success" href="javascript:history.back()">Guardar
								Cambios</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock body %}

principal/templates/principal/producto_form_vendedor.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{etiqueta}} Producto
{% endblock title %}

{% block css %}
{% endblock css %}

{% block body %}
{% load crispy_forms_tags %}
<br>
<div class="container justify-content-center">
	<div class="row">
		<div class="col-12 col-md-6 offset-md-3">
			<div class="card text-dark border-primary mb-3" style="max-width: 35rem;">
				<div class="card-body">
					<h4 class="card-title mb-4 mt-1">Nuevo Producto</h4>
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}                        
						{{form | crispy}}
						<br>

						<div class="d-flex justify-content-end">
							<button type="submit" class="btn btn-success" href="javascript:history.back()">Guardar</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock body %}

principal/templates/principal/servicio_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	Eliminar Servicio
{% endblock title %}

{% block body %}
	<form method="post">
		{% csrf_token %}
		<p>Quieres eliminar el servicio "{{ object }}"?</p>
		<input type="submit" value="Si, si quiero">
		<a href="{% url 'principal:lista' %}"><i class="fa fa-times"> </i>Mejor no</a>
	</form>
{% endblock body %}

principal/templates/principal/servicio_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	{{etiqueta}} Servicio
{% endblock title %}

{% block css %}
{% endblock css %}

{% block body %}
	<h1>{{etiqueta}} Servicio</h1>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">{{boton}}</button>
		<a href="javascript:history.back()">Regresar</a>
	</form>
{% endblock body %}