comerciov2/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('principal.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('ordenes/', include('ordenes.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordenes/urls.py
from django.urls import path
from . import views

app_name = 'ordenes'

urlpatterns = [
    path('agregar/', views.agregar_carrito, name="agregar"),
    path('carrito/', views.lista_carrito, name="lista_carrito"),
    path('comprar/', views.comprar, name="comprar"),
    path('cancelar-carrito/', views.cancelar_carrito, name='cancelar_carrito')
]

principal/urls.py
from django.urls import path

from . import views

app_name = 'principal'

urlpatterns = [
    # Home de la pagina
    path('', views.index, name='principal'),
    path('admin/', views.admin, name='admin'),

    # Listado de productos/servicios
    path('lista/', views.lista, name='lista'),

    # Listado de productos/servicios para administradores
    path('lista_admin/', views.lista_admin, name='lista_admin'),

    path('lista_productos_vendedor/', views.lista_productos,
         name='lista_prod_vendedor'),

    # CRUD Productos
    path('nuevo_producto/', views.NuevoProducto.as_view(), name='nuevo_producto'),
    path('editar_producto/<int:pk>',
         views.EditarProducto.as_view(), name='editar_producto'),
    path('eliminar_producto/<int:pk>',
         views.EliminarProducto.as_view(), name='eliminar_producto'),
    path('ver_producto/<int:pk>', views.VerProducto.as_view(), name='ver_producto'),
    path('nuevo_producto_vendedor/', views.AgregarProductoVendedor.as_view(),
         name='nuevo_producto_vendedor'),


    # CRUD Servicios
    path(
        'nuevo_servicio/',
        views.NuevoServicio.as_view(),
        name='nuevo_servicio'),
    path(
        'eliminar_servicio/<int:pk>',
        views.EliminarServicio.as_view(),
        name='eliminar_servicio')
]

ordenes/models.py
from django.db import models


class Orden(models.Model):
    fecha_compra = models.DateField(auto_now_add=True)
    usuario = models.CharField(max_length=150)


class DetalleOrden(models.Model):
    producto = models.ForeignKey(
        "principal.Producto",
        verbose_name="Producto",
        on_delete=models.CASCADE)
    orden = models.ForeignKey(
        "ordenes.Orden",
        verbose_name="Orden",
        on_delete=models.CASCADE)
    cantidad = models.IntegerField("Cantidad")
    precio = models.FloatField("Precio unitario")

ordenes/views.py
from ordenes.models import DetalleOrden, Orden
from django.shortcuts import render
from django.shortcuts import redirect, render, get_object_or_404
from principal.models import Producto
from django.contrib.auth.decorators import login_required, permission_required


@login_required
@permission_required('usuarios.permiso_usuario', raise_exception=True)
def agregar_carrito(request):
    if request.method == "POST":
        pk = request.POST.get('id')
        cantidad = 1
        producto = get_object_or_404(Producto, pk=pk)
        if producto.stock > 0:
            producto.stock -= int(cantidad)
            producto.save()
            id = str(pk)
            total = float(producto.precio) * float(cantidad)
            request.session['total'] = request.session['total'] + total
            request.session['cantidad'] = request.session['cantidad'] + \
                int(cantidad)

            if id in request.session['articulos']:
                request.session['articulos'][id]['cuantos'] = request.session['articulos'][id]['cuantos']
                + int(cantidad)
            else:
                request.session['articulos'][id] = {'precio': float(
                    producto.precio), 'cuantos': int(cantidad)}

    return redirect('ordenes:lista_carrito')


@login_required
@permission_required('usuarios.permiso_usuario', raise_exception=True)
def lista_carrito(request):
    articulos = request.session['articulos']
    total = request.session['total']
    cantidad = request.session['cantidad']
    datos = list()

    for articulo in articulos:
        prod = Producto.objects.get(id=int(articulo))
        item = {
            'imagen': prod.imagen,
            'nombre': prod.nombre,
            'precio': articulos[articulo]['precio'],
            'cantidad': articulos[articulo]['cuantos'],
            'subtotal': int(articulos[articulo]['precio']) * int(articulos[articulo]['cuantos'])
        }
        datos.append(item)

    context = {'datos': datos,
               'total': total,
               'cantidad': cantidad,
               }
    return render(request, 'lista_carrito.html', context=context)


@login_required
@permission_required('usuarios.permiso_usuario', raise_exception=True)
def comprar(request):
    orden = Orden(usuario=1)
    orden.save()

    articulos = request.session['articulos']

    for articulo in articulos:
        prod = Producto.objects.get(id=int(articulo))
        precio = articulos[articulo]['precio']
        cantidad = articulos[articulo]['cuantos']
        detail = DetalleOrden(
            producto=prod,
            orden=orden,
            cantidad=cantidad,
            precio=precio)
        detail.save()

    request.session['total'] = 0.0
    request.session['cantidad'] = 0
    request.session['articulos'] = {}

    return redirect('principal:principal')


@login_required
@permission_required('usuarios.permiso_usuario', raise_exception=True)
def cancelar_carrito(request):
    articulos = request.session['articulos']

    for articulo in articulos:
        prod = Producto.objects.get(id=int(articulo))
        cantidad = articulos[articulo]['cuantos']
        prod.stock = prod.stock + cantidad
        prod.save()

    request.session['total'] = 0.0
    request.session['cantidad'] = 0
    request.session['articulos'] = {}
    return redirect('principal:iniciar')

ordenes/templates/lista_carrito.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Mi Carrito
{% endblock title %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/mis_estilos.css'%}">
{% endblock css %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="page-header">
                Carrito de compra
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 mb-4">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <th></th>
                        <th class="mob-hide">Nombre</th>
                        <th class="mob-hide">Precio Unitario</th>
                        <th class="mob-hide">Cantidad</th>
                        <th>Subtotal</th>
                        <th></th>
                    </thead>
                    <tbody>
                        <tr>
                        {% for dato in datos %}
                            <tr>
                            <td>
                                <div class="imagen-carrito">
                                    <img src="{% if dato.imagen %}/media/{{MEDIA_URL}}{{dato.imagen}}{% else %}{% static 'images/product_placeholder.png' %}{% endif %}" alt="{{dato.nombre}}"> 
                                </div>
                            </td>
                            <td>{{dato.nombre}}</td>
                            <td>${{dato.precio}}</td>
                            <td>{{dato.cantidad}}</td>
                            <td>${{dato.subtotal }}</td>
                            </tr>
                        {% endfor %}
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-4 mb-4">
        <div class="row">
            <div class="col-12">
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <td colspan="1" class="text-left">
                                <strong>Total</strong>
                            </td>
                            <td colspan="1" class="text-right">
                                <strong>${{total}}</strong>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div>
                    <a class="btn btn-primary btn-block" href="{% url 'ordenes:comprar' %}"> Finalizar compra</a>
                    <a class="btn btn-link btn-block" href="{% url 'principal:principal'%}">← Continuar Comprando</a>
                    <a class="btn btn-danger btn-block" href="{% url 'ordenes:cancelar_carrito' %}"> Cancelar compra</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

{% block js %}
    <script src="{% static 'js/funciones.js'%}"></script>
{% endblock js %}