comerciov2/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('principal.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('ordenes/', include('ordenes.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordenes/urls.py
from django.urls import path
from . import views

app_name = 'ordenes'

urlpatterns = [
    path('agregar/', views.agregar_carrito, name="agregar"),
    path('carrito/', views.lista_carrito, name="lista_carrito"),
    path('comprar/', views.comprar, name="comprar"),
    path('cancelar-carrito/', views.cancelar_carrito, name='cancelar_carrito')
]

usuarios/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'usuarios'

urlpatterns = [

    # CRUD Usuarios
    path('', views.UsuariosList.as_view(), name='lista'),
    path('pruebona/', views.PruebaUsuarios.as_view(), name='pruebona'),
    path('nuevo/', views.NuevoUsuario.as_view(), name='nuevo'),
    path('ver/<int:pk>', views.UsuariosDetalle.as_view(), name='ver'),
    path('editar/<int:pk>', views.UsuariosActualizar.as_view(), name='editar'),
    path('eliminar/<int:pk>', views.UsuariosEliminar.as_view(), name='eliminar'),

    # Sesiones
    path('login/', views.LoginUsuario.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpUsuario.as_view(), name='signup'),
    path('signup/vendor/', views.Sign_up_usuario_vendedor.as_view(),
         name='signup_vendor'),
    path('activar/<slug:uid64>/<slug:token>',
         views.ActivarCuenta.as_view(), name='activar'),

    # Grupos
    path('cambia-grupo/<int:id_gpo>/<int:id_usuario>',
         views.cambia_grupo, name='cambia-grupo'),
    path('modificar-grupos/<int:id>', views.modificar_usuario_grupo,
         name='modificar_usuario_grupo'),

    # Municipios
    path('municipios/', views.obtiene_municipios, name='municipios'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ForeignKey


class Usuario(User):
    # estado = ForeignKey("usuarios.Estado",verbose_name="Estado",on_delete=CASCADE)
    # municipio = ForeignKey("usuarios.Municipio",verbose_name="Municipio",on_delete=CASCADE)
    foto = models.ImageField(
        "Foto de Perfil", upload_to="perfiles", blank=True, null=True)
    password2 = models.CharField(
        "Verfica tu contraseña", blank=False, null=False, max_length=62, default="")
    puede_vender = models.BooleanField(default=False)


class Usuario_Vendedor(User):
    # estado = ForeignKey("usuarios.Estado", verbose_name = "Estado", on_delete=CASCADE)
    # municipio = ForeignKey("usuarios.Municipio", verbose_name="Municipio", on_delete=CASCADE)
    foto_perfil = models.ImageField(
        "Foto de Perfil", upload_to="perfil", blank=True, null=True)
    direccion = models.CharField(
        "Direccion", max_length=255, null=False, blank=False, default="")
    telefono = models.CharField(
        "Telefono", max_length=10, null=False, blank=False, default="")
    password_rev = models.CharField(
        "Verifica tu contraseña", blank=False, null=False, max_length=62, default="")
    descripcion = models.CharField(
        "Descripcion", max_length=255, null=True, blank=True)


class Estado(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre


class Municipio(models.Model):
    nombre = models.CharField(max_length=50)
    estado = models.ForeignKey(
        'usuarios.Estado', verbose_name="Estado", on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

# class Permisos_Grupos(models.Model):
#     class Meta:
#         permissions = (('permiso_vendedores','Permiso creado para los vendedores'))

usuarios/forms.py
from django import forms
from .models import Usuario, Usuario_Vendedor
from django.contrib.auth.models import Group

# Clase que implementa un tipo de usuario personalizado.


class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario

        fields = ('first_name', 'username', 'password',
                  'password2', 'email', 'foto')

        widgets = {
            'password': forms.PasswordInput(),
            'password2': forms.PasswordInput()
        }

    # Método por el cual se guardan los usuarios.
    def save(self, commit=True):
        user = super(UsuarioForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    # Verifica que las contraseñas ingresadas coinsidan
    def clean_password(self, *args, **kwargs):
        if self.data['password'] != self.data['password2']:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return self.data['password']

# Clase de usuario vendedor


class Usuario_Vendedor_Form(forms.ModelForm):
    class Meta:
        model = Usuario_Vendedor

        # Campos que tendra este usuario.
        fields = ('first_name', 'username', 'password', 'password_rev',
                  'email', 'foto_perfil', 'direccion', 'telefono', 'descripcion')

        # Se especifica el tipo de widget que sera utilizado para algunos de los campos.
        widgets = {
            'password': forms.PasswordInput(),
            'password_rev': forms.PasswordInput(),
            'descripcion': forms.Textarea()
        }

    # Guarda al usuario registrado.
    def save(self, commit=True):
        user = super(Usuario_Vendedor_Form, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            my_group = Group.objects.get(name='vendedores')
            user.save()
            my_group.user_set.add(user)
        return user

    # Verifica que la contraseña ingresada y la confirmacion sean iguales, de lo contrario, la limpia.
    def clean_password(self, *args, **kwargs):
        if self.data['password'] != self.data['password_rev']:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return self.data['password']

usuarios/views.py
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites. shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.contrib.auth.mixins import PermissionRequiredMixin

from django.http import JsonResponse
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import ListView, TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .token import token_activacion
from .models import Usuario, Municipio, Usuario_Vendedor
from .forms import UsuarioForm, Usuario_Vendedor_Form

# CRUD Usuarios


class UsuariosList(PermissionRequiredMixin, ListView):
    permission_required = 'users.permiso_administradores'
    model = Usuario
    template_name = 'usuario_list.html'
    lista_grupos = Group.objects.all()
    paginate_by = 5

    extra_context = {
        'us_lista': True,
        'lista_grupos': lista_grupos
    }


class UsuariosDetalle(DetailView):
    model = Usuario


class NuevoUsuario(PermissionRequiredMixin, CreateView):
    permission_required = 'users.permiso_administradores'
    model = Usuario
    form_class = UsuarioForm
    success_url = reverse_lazy('usuarios:lista')

    extra_context = {
        'etiqueta': 'Nuevo',
        'boton': 'Agregar',
        'us_nuevo': True
    }


class PruebaUsuarios(CreateView):
    model = Usuario
    form_class = UsuarioForm
    template_name = 'prueba.html'
    success_url = reverse_lazy('usuarios:login')


class UsuariosActualizar(PermissionRequiredMixin, SuccessMessageMixin, UpdateView):
    permission_required = 'users.permiso_administradores'
    model = Usuario
    form_class = UsuarioForm
    extra_context = {'etiqueta': 'Actualizar', 'boton': 'Guardar'}
    success_url = reverse_lazy('usuarios:lista')
    success_message = "El usuario %(first_name)s se actualizo con exito"


class UsuariosEliminar(PermissionRequiredMixin, DeleteView):
    permission_required = 'users.permiso_administradores'
    model = Usuario
    success_url = reverse_lazy('usuarios:lista')


# Sesiones de Usuarios

class LoginUsuario(LoginView):
    template_name = 'login.html'

    def get_success_url(self):
        self.request.session['articulos'] = {}
        self.request.session['cantidad'] = 0
        self.request.session['total'] = 0.0

        return super().get_success_url()


class SignUpUsuario(CreateView):
    model = Usuario
    template_name = 'sign_up.html'
    form_class = UsuarioForm
    success_url = reverse_lazy('usuarios:login')

    extra_context = {
        'etiqueta': "Nuevo",
        'boton': "Agregar",
    }

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        dominio = get_current_site(self.request)
        uid = urlsafe_base64_encode(force_bytes(user.id))
        token = token_activacion.make_token(user)

        message = render_to_string('confirmar_cuenta.html',
                                   {
                                       'usuario': user,
                                       'dominio': dominio,
                                       'uid':  uid,
                                       'token': token,
                                   }
                                   )

        subject = 'Activación de Cuenta | Plataforma digital comercial'
        to = user.email

        email = EmailMessage(
            subject,
            message,
            to=[to],
        )

        email.content_subtype = 'html'

        email.send()

        return super().form_valid(form)


class Sign_up_usuario_vendedor(CreateView):
    model = Usuario_Vendedor
    template_name = 'sign_up_vendor.html'
    form_class = Usuario_Vendedor_Form

    success_url = reverse_lazy('usuarios:login')


class ActivarCuenta(TemplateView):
    def get(self, request, *args, **kwargs):
        try:
            uid = urlsafe_base64_decode(kwargs['uid64'])
            token = kwargs['token']
            user = Usuario.objects.get(id=uid)
        except:
            user = None

        if user and token_activacion.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(self.request, 'Cuenta activada con éxito')
        else:
            messages.error(
                self.request, 'Token inválido, contacta al administrador')

        return redirect('usuarios:login')


def cambia_grupo(request, id_gpo, id_usuario):
    grupo = Group.objects.get(id=id_gpo)
    usuario = Usuario.objects.get(id=id_usuario)
    if grupo in usuario.groups.all():
        if usuario.groups.count() <= 1:
            messages.error(
                request, 'El usuario debe pertenecer a un grupo como minimo')
        else:
            usuario.groups.remove(grupo)
            messages.success(
                request, f'El usuario {usuario} ya no  pertenece al grupo {grupo}')
    else:
        usuario.groups.add(grupo)
        messages.success(
            request, f'El usuario {usuario} se agrego al grupo {grupo}')
    return redirect('usuarios:lista')


def modificar_usuario_grupo(request, id):
    grupos = [grupo.id for grupo in Group.objects.all()]
    usuario = Usuario.objects.get(id=id)
    usuario.groups.clear()
    permission_required = 'usuarios.edit_usuario'

    for item in request.POST:
        if request.POST[item] == 'on':
            usuario.groups.add(Group.objects.get(id=int(item)))

        messages.success(request, f'El usuario {usuario} pertenece al grupo')

    return redirect('usuarios:lista')

# Metodo para municipios


def obtiene_municipios(request):
    if request.method == 'GET':
        return JsonResponse({'error': 'Petición incorrecta'}, safe=False,  status=403)
    id_estado = request.POST.get('id')
    municipios = Municipio.objects.filter(estado_id=id_estado)
    json = []
    if not municipios:
        json.append({'error': 'No se encontraron municipios para ese estado'})

    for municipio in municipios:
        json.append({'id': municipio.id, 'nombre': municipio.nombre})
    return JsonResponse(json, safe=False)

usuarios/templates/confirmar_cuenta.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmar cuenta</title>
</head>
<body>
    <div>
        <h3>Validar cuenta</h3>
        <p>Hola {{user.username}}</p>
        <p>Para completar tu registro en el sistema de <b>Plataforma comercial Digital</b> debes dar click en el siguiente enlace:
        </p>
        <br>
        <hr>
        <p>
            <a href="http://{{dominio}}{% url 'usuarios:activar' uid64=uid token=token %}">
                Activar mi cuenta
            </a>
        </p>
        <br>
        <p>Saludos!!!!</p>
    </div>
</body>
</html>

usuarios/templates/login.html
{% extends 'base.html' %}
{% load static %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

{% block title %}
Inicio Sesión
{% endblock title%}

{% block body %}
{% if form.errors %}
<div class="alert alert-warning">
	<p>Usuario no encontrado</p>
</div>
{% endif %}

{% if messages %}
{% for message in messages  %}
<div class="alert alert--{% if message.tags == 'error' %}danger{%else%}success{%endif%}">
	{{message}}
</div>
{% endfor %}
{% endif %}

<!-- Container del login-->
<div class="container justify-content-center" >
	<section class="vh-100">
		<div class="container-fluid">
			<div class="row">
			<div class="col-sm-6 text-black">
				<div class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">

				<form method="POST" style="width: 23rem;">
					{% csrf_token %}
					<h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Iniciar Sesión</h3>
					<div class="form-outline mb-4 form-group">
						<input id="id_username" name="username" type="text"
							class="form-control form-control-lg" required/>
						<label class="form-label" for="form2Example18">Usuario</label>
					</div>

					<div class="form-outline mb-4 form-group">
						<input type="password" class="form-control form-control-lg" id="id_password" name="password" type="password"
							required/>
						<label class="form-label" for="form2Example28">Contraseña</label>
					</div>

					<div class="pt-1 mb-4 form-group">
						<button class="btn-lg btn-block boton-ingresar" type="submit" >Ingresar</button>
					</div>
					<input type="hidden" name="next" value={{next}}>

					<p class="small mb-5 pb-lg-2 "><a class="crear-cuenta" href="reset-password.html">Olvidé la contraseña</a></p>
					<p>No tienes cuenta? <a href="{% url 'usuarios:signup' %}" class="link-info crear-cuenta">Crear cuenta</a></p>

				</form>

				</div>

			</div>
			<div class="col-sm-6 px-0 d-none d-sm-block">
				<img src="../../static/images/imagenes-tuneadas/Zacatecas.jpg" alt="Login image" class="imagen-zac" height="100%" style="object-fit: cover; object-position: left;">
			</div>
		</div>
	</div>
	</section>	
</div> <!-- container -->
	{% endblock body %}

usuarios/templates/prueba.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags%}

{% block title %}
Registrar
{% endblock title%}

{% block body %}
<h1> Prueba </h1>

<form method="post">
    {% csrf_token %}
    <div>
        <label class="control-label"> El nombre de usuario es: {{user.username}}</label>
        {% comment %} {{username | as_crispy_field}} {% endcomment %}
    </div>
</form>

{% endblock body%}

usuarios/templates/sign_up.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Registrar
{% endblock title%}
{% block body %}
{% load crispy_forms_tags%}

<br>
<div class="row">
	<div class="col-12 col-md-6 offset-md-3">
		<div class="card">
			<div class="card-body">
				<h1>Crear cuenta</h1>
				<form method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{{form | crispy }}
					<br>
					<br>
					<div class="d-flex justify-content-end">
						<button type="submit" class="btn boton-ingresar">Crear cuenta</button>
					</div>
				</form>
			</div>
			<p>¿Eres vendedor?<a href="{% url 'usuarios:signup_vendor'%}" class = "link-info crear-cuenta">Crear Cuenta Empresarial</a></p>
		</div>
	</div>
</div>


{% endblock body %}

{% block js %}
<script src="{% static 'js/funciones.js'%}"></script>
{% endblock js %}

usuarios/templates/sign_up_vendor.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Registro Vendedor
{% endblock title%}
{% block body %}
{% load crispy_forms_tags%}

<br>
<div class="row">
	<div class="col-12 col-md-6 offset-md-3">
		<div class="card">
			<div class="card-body">
				<h1>Crear cuenta</h1>
				<form method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{{form | crispy }}
					{% for field in form.visible_fields %}  
						{% for fieldName, label in fieldLabels %}
							{% if fieldName == field.field.widget.password  %}
								<div>
									<label>{{ label }}</label>
									{{ field }}
								</div>
							{% endif %}
						{% endfor %}
					{% endfor %}
					<br>
					<div class="d-flex justify-content-end">
						<button type="submit" class="btn boton-ingresar">Crear cuenta</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>


{% endblock body %}

{% block js %}
<script src="{% static 'js/funciones.js'%}"></script>
{% endblock js %}